name: hw-rankselect
version: '0.12.0.3'
synopsis: Rank-select
description: Please see README.md
category: Data, Conduit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-rankselect
homepage: http://github.com/haskell-works/hw-rankselect#readme
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3
extra-source-files:
- README.md
- data/README.md
- data/sample-000.idx
dependencies:
- hw-rankselect-base >=0.2.0.0 && < 0.4
- vector >= 0.12 && < 0.13

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.RankSelect.CsPoppy
  - HaskellWorks.Data.RankSelect.CsPoppy.Internal
  - HaskellWorks.Data.RankSelect.Poppy512
  dependencies:
  - base >=4 && <5
  - deepseq >= 1.4 && < 1.5
  - hw-balancedparens >=0.1.0.0 && < 0.3
  - hw-bits >=0.6.0.0 && < 0.8
  - hw-prim >=0.6 && < 0.7
  when:
  - condition: (impl(ghc >=8.0.1))
    ghc-options:
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  hw-rankselect:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - OverloadedStrings
    - TupleSections
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -O2
    - -msse4.2
    dependencies:
    - base >=4.7 && <5
    - directory >= 1.2 && < 1.4
    - hw-bits >=0.4.0.0 && < 0.8
    - hw-prim >=0.4.0.0 && < 0.7
    - hw-rankselect
    - lens >= 4 && < 5
    - mmap >= 0.5 && < 0.6
    - mtl >= 2.2 && < 2.3
    - optparse-applicative >= 0.11 && < 0.15
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
    when:
    - condition: (impl(ghc >=8.0.1))
      ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints

tests:
  hw-rankselect-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4 && <5
    - QuickCheck >= 2.10 && < 2.12
    - directory >= 1.2 && < 1.4
    - hedgehog >= 0.5 && < 0.7
    - hspec >= 2.4 && < 2.6
    - hw-bits >=0.4.0.0 && < 0.8
    - hw-hedgehog >=0.1.0.1 && < 0.2
    - hw-hspec-hedgehog >= 0.1 && < 0.2
    - hw-prim >=0.5.0.4 && < 0.7
    - hw-rankselect
    - mmap >= 0.5 && < 0.6
    - transformers >= 0.4 && < 0.6
    when:
    - condition: (impl(ghc >=8.0.1))
      ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -Wall
    - -msse4.2
    dependencies:
    - base >=4 && <5
    - bytestring >= 0.10 && < 0.11
    - conduit >= 1.2 && < 1.4
    - criterion >= 1.1 && < 1.5
    - directory >= 1.2 && < 1.5
    - hw-bits >=0.4.0.0 && < 0.8
    - hw-prim >=0.6.0.0 && < 0.7
    - hw-rankselect
    - hw-rankselect-base >=0.3.1.0 && < 0.4
    - mmap >= 0.5 && < 0.6
    - resourcet >= 1.1 && < 1.3
    when:
    - condition: (impl(ghc >=8.0.1))
      ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints

when:
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED

flags:
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
