resolver: nightly-2018-03-20

packages:
- '.'

extra-deps:
  - bits-extra-0.0.1.0
  - hedgehog-0.5.3
  - hw-hspec-hedgehog-0.1.0.4
  - hw-prim-0.6.0.0
  - hw-rankselect-base-0.3.1.0

flags: {}

extra-package-dbs: []
